"""adicao tabelas

Revision ID: 590aeb859f77
Revises: 
Create Date: 2025-12-14 12:05:40.472845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590aeb859f77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planta_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('nome_cientifico', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('familia', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('instrucoes_Cuidado', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('periodicidade_rega', sa.Integer(), nullable=True),
    sa.Column('periodicidade_poda', sa.Integer(), nullable=True),
    sa.Column('periodicidade_adubo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('super_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['super_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['super_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jardim',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planta_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('data_plantio', sa.Date(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('planta', sa.Integer(), nullable=True),
    sa.Column('jardim', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jardim'], ['jardim.id'], ),
    sa.ForeignKeyConstraint(['planta'], ['planta_catalogo.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('REGA', 'PODA', 'ADUBO', 'OUTOR', name='tipoacao'), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta_usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagem')
    op.drop_table('acao')
    op.drop_table('planta_usuario')
    op.drop_table('jardim')
    op.drop_table('usuario')
    op.drop_table('admin')
    op.drop_table('super_usuario')
    op.drop_table('planta_catalogo')
    # ### end Alembic commands ###
