"""Adicao tabela planta_usuario

Revision ID: 881367e43cff
Revises: d6666f43f01e
Create Date: 2025-12-08 17:49:57.030602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881367e43cff'
down_revision: Union[str, Sequence[str], None] = 'd6666f43f01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planta_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('nome_cientifico', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('familia', sa.String(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('instrucoes_Cuidado', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('periodicidade_Rega', sa.Integer(), nullable=True),
    sa.Column('periodicidade_Poda', sa.Integer(), nullable=True),
    sa.Column('periodicidade_Adubo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planta_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('apelido', sa.String(), nullable=True),
    sa.Column('data_plantio', sa.Date(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.Column('planta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planta'], ['planta_catalogo.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planta_usuario')
    op.drop_table('planta_catalogo')
    # ### end Alembic commands ###
